[platformio]
src_dir = .
include_dir = Core/Inc
[env]
framework = stm32cube
platform = ststm32
build_flags = -I ./Core/Inc/drivers -I ./USB_DEVICE/App -I ./USB_DEVICE/Target


[env:bluepill_f103c8]
board = bluepill_f103c8
